branches:
  only:
  - master
language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    - os: linux # 14.04
      dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
env:
  - CC=gcc-8
  - CXX=g++-8
before_install:
  - rustup component add clippy-preview rustfmt-preview
install:
  - npm install
script:
  - cargo build
  - cargo test
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
