branches:
  only:
  - master
language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    - os: linux # 14.04
      dist: trusty
addons:
  apt:
    packages:
      - gcc-4.9
      - g++-4.9
before_install:
  - rustup component add clippy-preview rustfmt-preview
install:
  - npm install
script:
  - cargo build
  - cargo test
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
