branches:
  only:
  - master
language: rust
rust:
  - nightly
cache:
  cargo: true
matrix:
  include:
    - os: linux # 14.04
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - autoconf2.13
before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - g++ -v
  # Cargo tries to lint all of the path dependencies, so it's disabled for now
  # https://github.com/rust-lang/rust-clippy/issues/1066
  # - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
  - rustup component add rustfmt || cargo install --git https://github.com/rust-lang/rustfmt/ --force rustfmt
  - cp ./servo/Cargo.lock .
script:
  - travis_wait 30 cargo build
  - cargo test
  # Cargo tries to lint all of the path dependencies, so it's disabled for now
  # https://github.com/rust-lang/rust-clippy/issues/1066
  # - cargo clippy --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
